backend = "glx";
glx-copy-from-front = false;

# Opacity
active-opacity = 1;
inactive-opacity = 1;
frame-opacity = 1;
inactive-opacity-override = false;
blurbackground = true;

# Blur
blur-method = "dual_kawase";
blur-strength = 6;
blur-background-exclude = [
  "window_type = 'menu'",
  "window_type = 'dropdown-menu'",
  "window_type = 'popup-menu'",
  "window_type = 'tooltip'",
  "class_g = 'Brave-browser' && window_type = 'utility'",
  "class_g = 'Brave-browser' && window_type = 'popup_menu'"
];

# Other
mark-wmwin-focused = true;
mark-overdir-focused = true;
detect-rounded-corners = true;
detect-client-opacity = true;
vsync = true;
dbe =  false;
underid-if-possible = false;
focus-exclude = [ ];
detect-transient = true;
detect-client-leader = true;

# Window type settings
wintypes:
{
    dock = {
        shadow = false;
    };
};

opacity-rule = [
    "90:class_g = 'kitty' && focused",
    "85:class_g = 'kitty' && !focused"
];

shadow = false;
shadow-radius = 12;
shadow-offset-x = -5;
shadow-offset-y = -5;
shadow-opacity = 0.5;
#shadow-green = 1.0;

corner-radius = 0

xrender-sync-fence = true;



